[path]
inserts = 'app/inserts'
layouts = 'app/layouts'
models = 'app/models'
routes = 'app/routes'
static = 'app/static'
output = 'build'

[build]
layout = 'default'
model = 'default'

[document]
favicon = true
lang = 'sv'